// import { SearchContextType } from '../components/context/SearchContext'; // Убедитесь, что импортируете правильный тип

import { CatBreed, CatsDataType } from '../types/types';

export const mockSearchContext = {
  idValue: 'some-id',
  setIdValue: vi.fn(),
  searchValue: '',
  limit: 10,
  breeds: [],
  cats: [],
  searchValueKey: '',
  currentPage: 1,
  setCurrentPage: vi.fn(),
  setSearchValueKey: vi.fn(),
  setCats: vi.fn(),
  setLimit: vi.fn(),
  setSearchValue: vi.fn(),
  setBreedsValue: vi.fn(),
  saveToLocalStorage: vi.fn(),
};

// Моковые данные о кошке (применяйте свой интерфейс CatBreed)
export const mockCat = {
  id: 'abys',
  name: 'Abyssinian',
  origin: 'Egypt',
  life_span: '12-15 years',
  cfa_url: 'https://cfa.org/abyssinian/',
  wikipedia_url: 'https://en.wikipedia.org/wiki/Abyssinian_cat',
  country_code: 'EG',
  country_codes: 'EG,US,CA,GB',
  adaptability: 4,
  affection_level: 5,
  child_friendly: 3,
  dog_friendly: 4,
  energy_level: 5,
  grooming: 2,
  health_issues: 2,
  hypoallergenic: 1,
  indoor: 1,
  intelligence: 4,
  lap: 3,
  natural: 1,
  rare: 0,
  shedding_level: 3,
  short_legs: 0,
  social_needs: 3,
  stranger_friendly: 3,
  suppressed_tail: 0,
  vocalisation: 3,
  weight: {
    imperial: '8 - 12 lbs',
    metric: '3.6 - 5.4 kg',
  },
  alt_names: 'Abyssinian Cat, Abyssinian Shorthair, Abys',
  experimental: 0,
  hairless: 0,
  description:
    'The Abyssinian is a breed of domestic short-haired cat with a distinctive ticked coat.',
  temperament: 'Active, Energetic, Independent, Intelligent, Gentle',
  vcahospitals_url: 'https://vcahospitals.com/abyssinian',
  vetstreet_url: 'https://www.vetstreet.com/cats/abyssinian',
};

export const mockDetaileCards = [
  {
    breeds: [
      {
        name: 'Breed Name',
        origin: 'Country',
        temperament: 'Friendly',
        description: 'Some description',
      },
    ],
  },
];

export const mockDataCatsData: CatsDataType[] = [
  {
    id: '1',
    url: 'https://example.com/1',
    breeds: [
      {
        name: 'Breed Name',
        origin: 'Country',
        temperament: 'Temperament',
        description: 'Description',
        weight: { imperial: '10', metric: '5' },
        wikipedia_url: 'https://wikipedia.com',
        id: '',
        life_span: '',
        cfa_url: '',
        country_code: '',
        country_codes: '',
        adaptability: 0,
        affection_level: 0,
        child_friendly: 0,
        dog_friendly: 0,
        energy_level: 0,
        grooming: 0,
        health_issues: 0,
        hypoallergenic: 0,
        indoor: 0,
        intelligence: 0,
        lap: 0,
        natural: 0,
        rare: 0,
        shedding_level: 0,
        short_legs: 0,
        social_needs: 0,
        stranger_friendly: 0,
        suppressed_tail: 0,
        vocalisation: 0,
        alt_names: '',
        experimental: 0,
        hairless: 0,
        vcahospitals_url: '',
        vetstreet_url: '',
      },
    ],
    height: 0,
    width: 0,
  },
  {
    id: '2',
    url: 'https://example.com/2',
    breeds: [
      {
        name: 'Breed Name 2',
        origin: 'Country 2',
        temperament: 'Temperament 2',
        description: 'Description 2',
        weight: { imperial: '15', metric: '7' },
        wikipedia_url: 'https://wikipedia.com',
        id: '',
        life_span: '',
        cfa_url: '',
        country_code: '',
        country_codes: '',
        adaptability: 0,
        affection_level: 0,
        child_friendly: 0,
        dog_friendly: 0,
        energy_level: 0,
        grooming: 0,
        health_issues: 0,
        hypoallergenic: 0,
        indoor: 0,
        intelligence: 0,
        lap: 0,
        natural: 0,
        rare: 0,
        shedding_level: 0,
        short_legs: 0,
        social_needs: 0,
        stranger_friendly: 0,
        suppressed_tail: 0,
        vocalisation: 0,
        alt_names: '',
        experimental: 0,
        hairless: 0,
        vcahospitals_url: '',
        vetstreet_url: '',
      },
    ],
    height: 0,
    width: 0,
  },
];

export const catBreed: CatBreed[] = [
  {
    id: '1',
    name: 'Abyssinian',
    origin: 'Ethiopia',
    life_span: '12-15 years',
    cfa_url: 'https://www.cfa.org/abyssinian',
    wikipedia_url: 'https://en.wikipedia.org/wiki/Abyssinian_cat',
    country_code: 'ET',
    country_codes: 'ET,US',
    adaptability: 4,
    affection_level: 5,
    child_friendly: 4,
    dog_friendly: 3,
    energy_level: 4,
    grooming: 3,
    health_issues: 2,
    hypoallergenic: 1,
    indoor: 1,
    intelligence: 4,
    lap: 5,
    natural: 1,
    rare: 1,
    shedding_level: 3,
    short_legs: 0,
    social_needs: 3,
    stranger_friendly: 2,
    suppressed_tail: 0,
    vocalisation: 4,
    weight: {
      imperial: '8 - 12 lbs',
      metric: '3.6 - 5.4 kg',
    },
    alt_names: 'Aby',
    experimental: 0,
    hairless: 0,
    description: 'The Abyssinian is a very energetic and playful cat.',
    temperament: 'Active, Intelligent, Friendly',
    vcahospitals_url: 'https://vcahospitals.com',
    vetstreet_url: 'https://www.vetstreet.com',
  },
  {
    id: '2',
    name: 'Ethiopi',
    origin: 'Ethiopia',
    life_span: '12-15 years',
    cfa_url: 'https://www.cfa.org/abyssinian',
    wikipedia_url: 'https://en.wikipedia.org/wiki/Abyssinian_cat',
    country_code: 'ET',
    country_codes: 'ET,US',
    adaptability: 4,
    affection_level: 5,
    child_friendly: 4,
    dog_friendly: 3,
    energy_level: 4,
    grooming: 3,
    health_issues: 2,
    hypoallergenic: 1,
    indoor: 1,
    intelligence: 4,
    lap: 5,
    natural: 1,
    rare: 1,
    shedding_level: 3,
    short_legs: 0,
    social_needs: 3,
    stranger_friendly: 2,
    suppressed_tail: 0,
    vocalisation: 4,
    weight: {
      imperial: '8 - 12 lbs',
      metric: '3.6 - 5.4 kg',
    },
    alt_names: 'Aby',
    experimental: 0,
    hairless: 0,
    description: 'The Abyssinian is a very energetic and playful cat.',
    temperament: 'Active, Intelligent, Friendly',
    vcahospitals_url: 'https://vcahospitals.com',
    vetstreet_url: 'https://www.vetstreet.com',
  },
];
