import { Options } from '@/types/restClient';

export const option: Options[] = ['JSON', 'Text'];
export const generatedCode = [
  'JavaScript-Fetch',
  'JavaScript-XHR',
  'Java-OkHttp',
  'Java-Unirest',
  'Go-Native',
  'csharp-HttpClient-C#',
  'curl-cURL',
  'NodeJs-Axios',
  'NodeJs-Request',
  'Python-http.client',
];
export const methods = [
  'GET',
  'POST',
  'PUT',
  'DELETE',
  'PATCH',
  'OPTIONS',
  'HEAD',
];
export const headerKeys = [
  'Accept',
  'Accept-Charset',
  'Accept-Encoding',
  'Accept-Language',
  'Accept-Ranges',
  'Authorization',
  'Cache-Control',
  'Connection',
  'Content-Length',
  'Content-MD5',
  'Content-Type',
  'Cookie',
  'Date',
  'Expect',
  'Forwarded',
  'From',
  'Host',
  'If-Match',
  'If-Modified-Since',
  'If-None-Match',
  'If-Range',
  'If-Unmodified-Since',
  'Max-Forwards',
  'Origin',
  'Pragma',
  'Proxy-Authorization',
  'Range',
  'Referer',
  'TE',
  'Trailer',
  'Transfer-Encoding',
  'Upgrade',
  'User-Agent',
  'Via',
  'Warning',
];
